solution: clrzmq4.mono.sln
language: csharp
mono: latest
#sudo: required

matrix:
  include:
    - os: linux
      dist: xenial

    - os: osx
      osx_image: xcode9.4
#      osx_image: xcode7.3

before_install:
  - chmod a+x ./travis.preinstall.sh
  - chmod a+x ./build.sh

install:
  - ./travis.preinstall.sh
  - ./build.sh

#before_script:

script:
  - mono bin/Release/ZGuideExamples.exe EAgain
  - mono bin/Release/ZGuideExamples.exe Espresso
  - mono bin/Release/ZGuideExamples.exe AsyncSrv
  - mono bin/Release/ZGuideExamples.exe SuiSnail
